name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t sushi-bar:latest .

      - name: Test Docker container
        run: |
          docker run -d --name sushi-bar-container -p 8080:80 sushi-bar:latest
          sleep 2
          curl --fail http://localhost:8080 || exit 1
